<a href="https://colab.research.google.com/github/SJJuunnY/Tensorflow/blob/main/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch

In [ ]:
print(pd.__version__)
print(np.__version__)
print(torch.__version__)

1.5.3
1.25.2
2.2.1+cu121


In [ ]:
# tensor 생성 (다차원 배열 == numpy 배열 )
x = torch.Tensor(2,3)
print(x)

tensor([[-3.2741e-08,  3.0984e-41,  5.0447e-44],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [ ]:
print(type(x)) # <class 'torch.Tensor'>
print(x.type()) # <class 'torch.Tensor'>

<class 'torch.Tensor'>
torch.FloatTensor


In [ ]:
print(x.size()) # torch.Size([2, 3])
print( np.array([1,2]).shape) # (2,)

torch.Size([2, 3])
(2,)


In [ ]:
#넘파이랑 비슷
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)
x = torch.ones(2,3,dtype=torch.int32)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
print(torch.rand(2,3))
print(torch.randn(2,3))
print(torch.eye(3,3))
print(torch.eye(2,3))

tensor([[0.1489, 0.5550, 0.1844],
        [0.2405, 0.4019, 0.5973]])
tensor([[ 0.3079,  0.2673,  0.5740],
        [-0.0558, -1.4895,  0.9087]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [ ]:
print(torch.arange(0,2,step=0.5))
print(torch.Tensor([[1,2,3],[1,2,3]]))

tensor([0.0000, 0.5000, 1.0000, 1.5000])
tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [ ]:
print(torch.IntTensor(2,3))
print(torch.BFloat16TensorTensor(2,3))

tensor([[-673538368,      22106,  699034848],
        [     32510,         80,          0]], dtype=torch.int32)
tensor([[3.8096e-14, 4.5556e-41, 3.7951e-14],
        [4.5556e-41, 4.1564e-14, 4.5556e-41]])


In [ ]:
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))
x = torch.from_numpy(x)
print(x,type(x))
y = x.numpy()
print(y, type(y))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [1, 2, 3]]) <class 'torch.Tensor'>
[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [ ]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
#slice indexing
print(x[:,1:]) # 행 다가져오고 열은 2번째부터
print(x[1:,1:2]) #행 2번째 이후로만 가져오고, 열은 2번째만

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])
tensor([[ 6.],
        [10.]])


In [ ]:
print(x)
x_rows = torch.split(x, split_size_or_sections=2, dim=1 ) # 1행식 잘라서 배열로 저장하자 dim=0 => 행, 1=> 열
print(x_rows)
print(type(x_rows))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))
<class 'tuple'>


In [ ]:
torch.chunk(x, chunks=2, dim=1) # 어 torch.split(x, split_size_or_sections=2, dim=1) 랑 똑같네

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [ ]:
torch.BoolTensor([[1,0,0],[0,1,1]])

tensor([[ True, False, False],
        [False,  True,  True]])